export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const SIMILAR_PRODUCTS_REQUEST = "SIMILAR_PRODUCTS_REQUEST";
export const SIMILAR_PRODUCTS_SUCCESS = "SIMILAR_PRODUCTS_SUCCESS";
export const SIMILAR_PRODUCTS_FAIL = "SIMILAR_PRODUCTS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
