export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const SELLER_PRODUCT_REQUEST = "SELLER_PRODUCT_REQUEST";
export const SELLER_PRODUCT_SUCCESS = "SELLER_PRODUCT_SUCCESS";
export const SELLER_PRODUCT_FAIL = "SELLER_PRODUCT_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const SIMILAR_PRODUCTS_REQUEST = "SIMILAR_PRODUCTS_REQUEST";
export const SIMILAR_PRODUCTS_SUCCESS = "SIMILAR_PRODUCTS_SUCCESS";
export const SIMILAR_PRODUCTS_FAIL = "SIMILAR_PRODUCTS_FAIL";

export const BEST_PRODUCTS_REQUEST = "BEST_PRODUCTS_REQUEST";
export const BEST_PRODUCTS_SUCCESS = "BEST_PRODUCTS_SUCCESS";
export const BEST_PRODUCTS_FAIL = "BEST_PRODUCTS_FAIL";

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
